# -*- coding: utf-8 -*-
"""Fetch Rewards Assesment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YRxPjdLv2MKxIH6e7scfX3wz_XNfrOsx

# For more detailed report , refer to the attached pdf document
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd drive/MyDrive
# %cd Fetch\ Rewards\ CSV

"""# Importing Necessary Libraries"""

import pandas as pd
import numpy as np
import math

"""# Reading USERS table"""

users = pd.read_csv('users.csv')
users.head()

users.columns=["id","active","createdDate","lastLogin","role","signUpSource","state"]

"""# ISSUE 1 : Finding Duplicate Records"""

users.id.value_counts().sort_values(ascending=False)[:20]

"""## Shape of original table"""

users.shape

"""## Dropping duplicates"""

users_no_duplicates = users.copy()
users_no_duplicates = users_no_duplicates.drop_duplicates()

"""## Shape of non-duplicate data"""

users_no_duplicates.shape

"""# ISSUE 2 : Removing ROLE column in USER Table"""

users_no_duplicates = users_no_duplicates.drop("role",axis=1)

users_no_duplicates.head()

"""# Reading BRANDS Table"""

brands = pd.read_csv('brands.csv')
brands.head()

brands.columns = ["id","barcode","brandCode","category","categoryCode","cpg_id","cpg_ref","name","topBrand"]

"""# ISSUE 3: Too many NULL values

## Number of missing values per column
"""

brands.isnull().sum()

"""# ISSUE 4 : Numerous test values

## Creating subset containing test Entries
"""

brands_test = brands[brands['name'].str.contains('test brand')]

brands_test.head()

"""## Shape of original Dataset"""

brands.shape

"""## Category Frequency of original Dataset"""

brands.category.value_counts()

"""## Shape of test entries Dataset"""

brands_test.shape

"""## Category Frequency of test entries dataset"""

brands_test.category.value_counts()

brands_new=pd.concat([brands,brands_test]).drop_duplicates(keep=False)

"""## Dataset with no test entries"""

brands_new.head()

"""## Shape of dataset with no test entries"""

brands_new.shape

"""## Category Frequency of Dataset with no test entries"""

brands_new.category.value_counts()

"""# Issue 5 :  Columns have mixed datatypes in Brands table

## Columns having numeric brandCode values have most values similar to barcode
"""

brands[brands.brandCode.str.isnumeric()==True][:10]

"""# Reading Receipts data

## ISSUE 6 : Receipts data has rewardsreceiptItemsList which has nested column violating 1NF or atomicity
"""

receipts = pd.read_csv('receipts.csv')
receipts.head()

receipts.info()

cols1  = receipts.iloc[: , :11]
cols2  = receipts.iloc[: , 23:26]

receipt_fin = pd.concat([cols1,cols2],axis=1)

receipt_fin.head()

"""# Analyzing null Values"""

receipt_fin.isna().sum()

receipt_fin.rewardsReceiptStatus.value_counts()

"""# ISSUE 7 : Receipts with Status "Submitted" has most of the columns null. Consumes Storage space"""

receipts_sub=receipt_fin[receipt_fin.rewardsReceiptStatus=='SUBMITTED']

receipts_sub.shape

receipts_sub.isnull().sum()